# Generated by Django 3.2.3 on 2021-06-15 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='animal',
            fields=[
                ('id_animal', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id animal')),
                ('tipo_animal', models.CharField(max_length=50, verbose_name='tipo de animal')),
            ],
        ),
        migrations.CreateModel(
            name='mascotas',
            fields=[
                ('numero', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='numero de chip')),
                ('nombre', models.CharField(max_length=20, verbose_name='nombre mascota')),
                ('edad', models.CharField(max_length=20, null=True, verbose_name='edad nacimiento')),
                ('img_mascota', models.ImageField(null=True, upload_to='mascota')),
                ('id_tipo_animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.animal')),
            ],
        ),
    ]
