# Generated by Django 3.2.3 on 2021-06-24 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_mascotas_img_mascota'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id_genero', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Genero')),
                ('nom_genero', models.CharField(max_length=10, verbose_name='Genero')),
            ],
        ),
        migrations.AlterField(
            model_name='mascotas',
            name='img_mascota',
            field=models.ImageField(null=True, upload_to='mascota', verbose_name='imagen mascota'),
        ),
        migrations.AddField(
            model_name='mascotas',
            name='id_genero',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.genero'),
            preserve_default=False,
        ),
    ]
