# Generated by Django 3.2.3 on 2021-06-24 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210624_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascotas',
            name='edad',
            field=models.CharField(max_length=20, null=True, verbose_name='edad'),
        ),
    ]
