# Generated by Django 3.2.3 on 2021-06-24 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_mascotas_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascotas',
            name='edad',
            field=models.CharField(max_length=20, null=True, verbose_name='Edad'),
        ),
        migrations.AlterField(
            model_name='mascotas',
            name='id_genero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.genero', verbose_name='Genero'),
        ),
        migrations.AlterField(
            model_name='mascotas',
            name='id_tipo_animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.animal', verbose_name='Animal'),
        ),
        migrations.AlterField(
            model_name='mascotas',
            name='img_mascota',
            field=models.ImageField(null=True, upload_to='mascota', verbose_name='Imagen Mascota'),
        ),
        migrations.AlterField(
            model_name='mascotas',
            name='nombre',
            field=models.CharField(max_length=20, verbose_name='Nombre Mascota'),
        ),
        migrations.AlterField(
            model_name='mascotas',
            name='numero',
            field=models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Numero de Chip'),
        ),
    ]
